<?php
bolt_decrypt( __FILE__ , 'Lya1kk'); return 0;
##!!!##NzebjpqSoJ2OkJJNbp2daDc3oqCSTXaZmaKalpuOoZKJcY6hjo+OoJKJcpmcnqKSm6GJepyRkploNzeQmY6goE2CoJKfgY6gmE2SpaGSm5GgTXqckZKZN6g3TU1NTVxcN01NTU2dn5yhkpChkpFNUaGOj5mSTWpNT6Kgkp+MoY6gmKBPaDc3TU1NTZ2ij5mWkE2TopuQoZacm02QnJqakpuhoFVWqDdNTU1NTU1NTZ+SoaKfm01RoZWWoFprlY6geo6bplWBjqCYcJyampKboWdnkJmOoKBZVKKgkp+MoY6gmIyWkVRWaDdNTU1NqjeqNw==